### ISSUE TITLE
Naming inconsistency of the CelebA experiment: "CelebA_Blond" or "CelebA_Blonde" ?

### ISSUE THREAD

**Issue by alexrame** [ynysjtu/ood_bench#2]
Thank you for the great work and for open-sourcing your benchmark. I believe there is a naming inconsistency for your CelebA experiment.

The dataset is named "CelebA_Blond" here https://github.com/ynysjtu/ood_bench/blob/cac82a5ea97a9d4772066fe40a17d7db185e9615/DomainBed/domainbed/datasets.py#L53 .

In contrast, you define hyperparameter distributions for the "CelebA_Blonde" dataset (with an "e" at the end) here https://github.com/ynysjtu/ood_bench/blob/cac82a5ea97a9d4772066fe40a17d7db185e9615/DomainBed/domainbed/hparams_registry.py#L136

So overall, you may need to fix this. Moreover, could this affect the results reported in your paper? 
Thanks in advance

**Comment by m-Just** [comment]
Thank you for letting us know! We've fixed this in commit [0e5d6c](https://github.com/ynysjtu/ood_bench/commit/0e5d6c3fa8c8b7434c92934938216dd02cc389cf). We also checked the history and the conclusion is that it does not affect the results reported in our paper. "CelebA_Blonde" was the original one and later we changed it to "CelebA_Blond" for simplicity during code cleanup after the experiments.
