### ISSUE TITLE
Some images are in both the train and test split of NICO dataset?

### ISSUE THREAD

**Issue by lihaoxin05** [ynysjtu/ood_bench#3]
Hi. Thank you for the great work. However, I found that some images in the NICO dataset appear in both the provided train and test split. For example, truck\on_grass\34.jpg are in both datasets/NICO/mixed_split/env_test.csv and datasets/NICO/mixed_split/env_train1.csv. Could you please check if there is any error in the provided splits of NICO dataset? Or is that how it should be? Thanks.

**Comment by m-Just** [comment]
Thank you for pointing this out! It turns out there's a bug in the split generating code for NICO. Please refrain from using the split files provided under "mixed_split". The correct one is now under "mixed_split_corrected". Corresponding experiment results will be updated to our paper later.

**Comment by lihaoxin05** [comment]
Thanks for your reply.
