### ISSUE TITLE
[Question] the diversity and correlation shifts of the VLCS dataset

### ISSUE THREAD

**Issue by dnap512** [ynysjtu/ood_bench#5]
Hi!
I read your great work and am interested in this paper.
I'm curios about the diversity and correlation shifts of the VLCS dataset.
Could you please share these?

Thank you for your great research.

**Comment by m-Just** [comment]
Hi @dnap512, sorry for the late reply. We were busy refactoring the code for the full release. You can find all the code now at https://github.com/m-Just/OoD-Bench. Unfortunately, we do not have the diversity shift and correlation shift for VLCS. You're welcome to experiment with VLCS and find them out using our code. This repository is deprecated and will be deleted soon.
